apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dt6w8249v-python
  janus-idp.io/tekton: dt6w8249v-python
  backstage.io/kubernetes-id: dt6w8249v-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dt6w8249v-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
