apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dt6w8249v-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dt6w8249v-python 
  name: dt6w8249v-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dt6w8249v-python 
